import type { NextPage } from 'next';
import Head from 'next/head';
import { useLoginStatus } from '../hooks/useLoginStatus';
import styles from '../styles/pages/Gift.module.scss';

const MyPage: NextPage = () => {
    const isLogin = useLoginStatus();

    if (isLogin == null) return <div>loading...</div>;

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.content}>{isLogin ? <h1>login</h1> : <h1>not login</h1>}</div>
        </>
    );
};

export default MyPage;
