import type { NextPage } from 'next';
import Head from 'next/head';
import { useLoginStatus } from '../hooks/useLoginStatus';
import { Button, Card } from 'react-bulma-components';

const MyPage: NextPage = () => {
	const isLogin = useLoginStatus();

	if (isLogin == null) return <div>loading...</div>;

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="title pagetitle">寄付・サブスク登録</h1>
			<Card>
				<h1 className="title">1回きりの決済による寄付</h1>
				<p>
					1回の決済による単発の寄付です。 <br />
					スライダーを動かして金額を設定し、「寄付する」ボタンを押すと、決済ページへ移動します。
				</p>
				{isLogin ? (
					<>
						<p>ここにユーザ情報が入ります。</p>
					</>
				) : (
					<p>右上のログインボタンからログインしてください。</p>
				)}
				<Button className="is-primary" fullwidth={true}>
					寄付する
				</Button>
			</Card>

			<Card>
				<h1 className="title">サブスクリプション（毎月のお支払い）の登録</h1>
				<p>
					毎月決済が行われるサブスクリプションです。
					<br />
					月ごとにお支払いいただく金額を下記から選択し、「登録する」ボタンを押すと、決済ページへ移動します。
				</p>
				<Button className="is-primary" fullwidth={true}>
					寄付する
				</Button>
			</Card>
		</>
	);
};

export default MyPage;
